language: c

env:
 matrix:
  - MONO_VERSION="3.2.5"

before_install:
  - sudo bash -c "echo deb http://badgerports.org precise main >> /etc/apt/sources.list"
  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 0E1FAD0C
  - sudo apt-get update -qq
  - sudo apt-get install -qq mono-devel

install:
  - mozroots --import --sync --quiet
  - mono ./nuget/NuGet.exe restore ./ArcGIS.PCL.XamarinMaps/ArcGIS.PCL.XamarinMaps.sln

script:
  - xbuild ./ArcGIS.PCL.XamarinMaps/ArcGIS.PCL.XamarinMaps.ci.csproj

notifications:
  email:
    - dwtimmins@outlook.com
