language: objective-c

env:
  matrix:
    - MONO_VERSION="3.6.0"

install:
  - wget "http://download.mono-project.com/archive/${MONO_VERSION}/macos-10-x86/MonoFramework-MDK-${MONO_VERSION}.macos10.xamarin.x86.pkg"
  - sudo installer -pkg "MonoFramework-MDK-${MONO_VERSION}.macos10.xamarin.x86.pkg" -target /
  - mono ./nuget/NuGet.exe restore ./ArcGIS.PCL.XamarinMaps/ArcGIS.PCL.XamarinMaps.sln

script:
  - xbuild ./ArcGIS.PCL.XamarinMaps/ArcGIS.PCL.XamarinMaps.sln /property:Configuration=Release /nologo /verbosity:normal

notifications:
  email:
    - dwtimmins@outlook.com
